//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppVezhba
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimAccount_FactFinance_View1
    {
        public string ValueType { get; set; }
        public string AccountDescription { get; set; }
        public string Operator { get; set; }
        public string AccountType { get; set; }
        public double Amount { get; set; }
    }
}
