//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppVezhba
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimReseller_DimGeogrpahy_FactResellerSales_View1
    {
        public string BusinessType { get; set; }
        public string ResellerName { get; set; }
        public string ProductLine { get; set; }
        public string AddressLine1 { get; set; }
        public string Phone { get; set; }
        public Nullable<int> NumberEmployees { get; set; }
        public string OrderFrequency { get; set; }
        public string StateProvinceName { get; set; }
        public string EnglishCountryRegionName { get; set; }
        public string City { get; set; }
        public string IpAddressLocator { get; set; }
        public string PostalCode { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<decimal> SalesAmount { get; set; }
        public Nullable<decimal> TaxAmt { get; set; }
        public Nullable<decimal> TotalProductCost { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
    }
}
